<?php
if (!defined('IN_MYBB')) { die('No direct access'); }

/** Lightweight catalogue shared by lifecycle writers; no hooks or template writes. */
function af_adaptivethemeframework_template_seeds(): array
{
    return [
        'index' => __DIR__ . '/templates/index.html',
        // Global breadcrumb presentation while ATF owns the active theme. Core
        // continues to build breadcrumb data/routes; ATF only replaces markup.
        'nav' => __DIR__ . '/templates/nav.html',
        'nav_bit' => __DIR__ . '/templates/nav_bit.html',
        'nav_bit_active' => __DIR__ . '/templates/nav_bit_active.html',
        // MyBB 1.8.40 build_forumbits() selects this template for each visible
        // top-level category and supplies its already permission-filtered children.
        'forumbit_depth1_cat' => __DIR__ . '/templates/forumbit_depth1_cat.html',
        'forumbit_depth2_forum' => __DIR__ . '/templates/forumbit_depth2_forum.html',
        'forumbit_depth2_forum_lastpost' => __DIR__ . '/templates/forumbit_depth2_forum_lastpost.html',
        'forumdisplay' => __DIR__ . '/templates/forumdisplay.html',
        // The stock subforum wrapper is a table. Once depth2 forums are semantic
        // articles, browsers foster-parent those articles outside the table,
        // leaving an empty category bar between subforums and topic cards.
        'forumdisplay_subforums' => __DIR__ . '/templates/forumdisplay_subforums.html',
        // Own the list wrapper as well as its rows: putting semantic <article>
        // cards directly in the stock <tbody> makes browsers foster-parent them
        // outside the list and visually splits the last-post content.
        'forumdisplay_threadlist' => __DIR__ . '/templates/forumdisplay_threadlist.html',
        'forumdisplay_threadlist_rating' => __DIR__ . '/templates/forumdisplay_threadlist_rating.html',
        'forumdisplay_threads_sep' => __DIR__ . '/templates/forumdisplay_threads_sep.html',
        'forumdisplay_thread' => __DIR__ . '/templates/forumdisplay_thread.html',
        'member_profile' => __DIR__ . '/templates/member_profile.html',
        'reputation' => __DIR__ . '/templates/reputation.html',
        'reputation_vote' => __DIR__ . '/templates/reputation_vote.html',
        'reputation_no_votes' => __DIR__ . '/templates/reputation_no_votes.html',
        // Task 37 proved these five stock member-list templates participate in
        // layout. Nested avatar/group/star/order templates remain core-owned.
        'memberlist' => __DIR__ . '/templates/memberlist.html',
        'memberlist_user' => __DIR__ . '/templates/memberlist_user.html',
        'memberlist_search' => __DIR__ . '/templates/memberlist_search.html',
        'memberlist_error' => __DIR__ . '/templates/memberlist_error.html',
        'memberlist_referrals_bit' => __DIR__ . '/templates/memberlist_referrals_bit.html',
        // Task 44 owns the proven full-document ModCP roots. Later staged
        // tasks may add only the child presentation required by the surface
        // being migrated; unrelated forms/fragments remain core-owned.
        'modcp' => __DIR__ . '/templates/modcp.html',
        'modcp_reports' => __DIR__ . '/templates/modcp_reports.html',
        'modcp_reports_allreports' => __DIR__ . '/templates/modcp_reports_allreports.html',
        'modcp_modlogs' => __DIR__ . '/templates/modcp_modlogs.html',
        'modcp_announcements' => __DIR__ . '/templates/modcp_announcements.html',
        'modcp_announcements_new' => __DIR__ . '/templates/modcp_announcements_new.html',
        'modcp_announcements_edit' => __DIR__ . '/templates/modcp_announcements_edit.html',
        'modcp_announcements_delete' => __DIR__ . '/templates/modcp_announcements_delete.html',
        'modcp_modqueue_threads' => __DIR__ . '/templates/modcp_modqueue_threads.html',
        'modcp_modqueue_posts' => __DIR__ . '/templates/modcp_modqueue_posts.html',
        'modcp_modqueue_attachments' => __DIR__ . '/templates/modcp_modqueue_attachments.html',
        'modcp_modqueue_empty' => __DIR__ . '/templates/modcp_modqueue_empty.html',
        'modcp_finduser' => __DIR__ . '/templates/modcp_finduser.html',
        'modcp_editprofile' => __DIR__ . '/templates/modcp_editprofile.html',
        'modcp_warninglogs' => __DIR__ . '/templates/modcp_warninglogs.html',
        'modcp_ipsearch' => __DIR__ . '/templates/modcp_ipsearch.html',
        'modcp_banning' => __DIR__ . '/templates/modcp_banning.html',
        'modcp_banuser' => __DIR__ . '/templates/modcp_banuser.html',

        // Task 45 migrates only the child presentation that is exclusive to
        // Overview, Moderator Log and All Reports. Shared ban-row fragments
        // remain core-owned until the dedicated bans task.
        'modcp_awaitingmoderation' => __DIR__ . '/templates/modcp_awaitingmoderation.html',
        'modcp_awaitingthreads' => __DIR__ . '/templates/modcp_awaitingthreads.html',
        'modcp_awaitingposts' => __DIR__ . '/templates/modcp_awaitingposts.html',
        'modcp_awaitingattachments' => __DIR__ . '/templates/modcp_awaitingattachments.html',
        'modcp_awaitingmoderation_none' => __DIR__ . '/templates/modcp_awaitingmoderation_none.html',
        'modcp_latestfivemodactions' => __DIR__ . '/templates/modcp_latestfivemodactions.html',
        'modcp_modlogs_result' => __DIR__ . '/templates/modcp_modlogs_result.html',
        'modcp_modlogs_noresults' => __DIR__ . '/templates/modcp_modlogs_noresults.html',
        'modcp_modlogs_nologs' => __DIR__ . '/templates/modcp_modlogs_nologs.html',
        'modcp_modlogs_multipage' => __DIR__ . '/templates/modcp_modlogs_multipage.html',
        'modcp_reports_allreport' => __DIR__ . '/templates/modcp_reports_allreport.html',
        'modcp_reports_allnoreports' => __DIR__ . '/templates/modcp_reports_allnoreports.html',

        // Task 46: only the child presentation required by Open Reports and
        // the three moderation queues. Core continues to own queries, scope,
        // processing, radio values, report cookies and redirects.
        'modcp_reports_report' => __DIR__ . '/templates/modcp_reports_report.html',
        'modcp_reports_noreports' => __DIR__ . '/templates/modcp_reports_noreports.html',
        'modcp_reports_selectall' => __DIR__ . '/templates/modcp_reports_selectall.html',
        'modcp_modqueue_threads_thread' => __DIR__ . '/templates/modcp_modqueue_threads_thread.html',
        'modcp_modqueue_threads_empty' => __DIR__ . '/templates/modcp_modqueue_threads_empty.html',
        'modcp_modqueue_posts_post' => __DIR__ . '/templates/modcp_modqueue_posts_post.html',
        'modcp_modqueue_posts_empty' => __DIR__ . '/templates/modcp_modqueue_posts_empty.html',
        'modcp_modqueue_attachments_attachment' => __DIR__ . '/templates/modcp_modqueue_attachments_attachment.html',
        'modcp_modqueue_attachments_empty' => __DIR__ . '/templates/modcp_modqueue_attachments_empty.html',
        'modcp_modqueue_masscontrols' => __DIR__ . '/templates/modcp_modqueue_masscontrols.html',

        // Task 47: exclusive read/search presentation for IP Search, Warning
        // Log and Find User. Shared edit-profile fragments stay untouched for
        // Task 48; MyBB continues to own queries, filters and authorization.
        'modcp_ipsearch_results' => __DIR__ . '/templates/modcp_ipsearch_results.html',
        'modcp_ipsearch_result' => __DIR__ . '/templates/modcp_ipsearch_result.html',
        'modcp_ipsearch_noresults' => __DIR__ . '/templates/modcp_ipsearch_noresults.html',
        'modcp_ipsearch_misc_info' => __DIR__ . '/templates/modcp_ipsearch_misc_info.html',
        'modcp_warninglogs_warning' => __DIR__ . '/templates/modcp_warninglogs_warning.html',
        'modcp_warninglogs_warning_revoked' => __DIR__ . '/templates/modcp_warninglogs_warning_revoked.html',
        'modcp_warninglogs_nologs' => __DIR__ . '/templates/modcp_warninglogs_nologs.html',
        'modcp_finduser_user' => __DIR__ . '/templates/modcp_finduser_user.html',
        'modcp_finduser_noresults' => __DIR__ . '/templates/modcp_finduser_noresults.html',

        // Task 48: only ModCP-exclusive edit-profile fragments are added to
        // ownership. Shared usercp_profile_* templates remain under their
        // existing UCP/APF ownership boundary and are reused as rendered data.
        'modcp_editprofile_signature' => __DIR__ . '/templates/modcp_editprofile_signature.html',
        'modcp_editprofile_suspensions_info' => __DIR__ . '/templates/modcp_editprofile_suspensions_info.html',

        // Task 49: ban presentation. The shared modcp_banning_ban child is
        // intentionally owned now that both the dedicated ban list and the
        // Task 45 overview consume the same semantic card shape.
        'modcp_banning_ban' => __DIR__ . '/templates/modcp_banning_ban.html',
        'modcp_banning_edit' => __DIR__ . '/templates/modcp_banning_edit.html',
        'modcp_banning_remaining' => __DIR__ . '/templates/modcp_banning_remaining.html',
        'modcp_banning_nobanned' => __DIR__ . '/templates/modcp_banning_nobanned.html',
        'modcp_nobanned' => __DIR__ . '/templates/modcp_nobanned.html',
        'modcp_banuser_addusername' => __DIR__ . '/templates/modcp_banuser_addusername.html',
        'modcp_banuser_editusername' => __DIR__ . '/templates/modcp_banuser_editusername.html',
        'modcp_banuser_bangroups' => __DIR__ . '/templates/modcp_banuser_bangroups.html',
        'modcp_banuser_lift' => __DIR__ . '/templates/modcp_banuser_lift.html',

        // Task 50: ModCP-exclusive announcement presentation. Public
        // announcement_* templates remain core-owned; ATF does not alter
        // announcement storage, parsing, permissions or mutation routes.
        'modcp_announcements_global' => __DIR__ . '/templates/modcp_announcements_global.html',
        'modcp_announcements_forum' => __DIR__ . '/templates/modcp_announcements_forum.html',
        'modcp_announcements_forum_nomod' => __DIR__ . '/templates/modcp_announcements_forum_nomod.html',
        'modcp_announcements_announcement' => __DIR__ . '/templates/modcp_announcements_announcement.html',
        'modcp_announcements_announcement_global' => __DIR__ . '/templates/modcp_announcements_announcement_global.html',
        'modcp_no_announcements_global' => __DIR__ . '/templates/modcp_no_announcements_global.html',
        'modcp_no_announcements_forum' => __DIR__ . '/templates/modcp_no_announcements_forum.html',
        'modcp_announcements_allowhtml' => __DIR__ . '/templates/modcp_announcements_allowhtml.html',

        'usercp' => __DIR__ . '/templates/usercp.html',
        'usercp_currentavatar' => __DIR__ . '/templates/usercp_currentavatar.html',
        'usercp_notepad' => __DIR__ . '/templates/usercp_notepad.html',
        'usercp_latest_threads' => __DIR__ . '/templates/usercp_latest_threads.html',
        'usercp_latest_threads_threads' => __DIR__ . '/templates/usercp_latest_threads_threads.html',
        'usercp_latest_subscribed' => __DIR__ . '/templates/usercp_latest_subscribed.html',
        'usercp_latest_subscribed_threads' => __DIR__ . '/templates/usercp_latest_subscribed_threads.html',
        'usercp_warnings' => __DIR__ . '/templates/usercp_warnings.html',
        'usercp_warnings_warning' => __DIR__ . '/templates/usercp_warnings_warning.html',
        'usercp_warnings_warning_post' => __DIR__ . '/templates/usercp_warnings_warning_post.html',
        'usercp_profile' => __DIR__ . '/templates/usercp_profile.html',
        'usercp_profile_away' => __DIR__ . '/templates/usercp_profile_away.html',
        'usercp_profile_website' => __DIR__ . '/templates/usercp_profile_website.html',
        'usercp_profile_customtitle' => __DIR__ . '/templates/usercp_profile_customtitle.html',
        'usercp_profile_customtitle_currentcustom' => __DIR__ . '/templates/usercp_profile_customtitle_currentcustom.html',
        'usercp_profile_customtitle_reverttitle' => __DIR__ . '/templates/usercp_profile_customtitle_reverttitle.html',
        'usercp_profile_profilefields' => __DIR__ . '/templates/usercp_profile_profilefields.html',
        'usercp_avatar' => __DIR__ . '/templates/usercp_avatar.html',
        'usercp_avatar_current' => __DIR__ . '/templates/usercp_avatar_current.html',
        'usercp_avatar_upload' => __DIR__ . '/templates/usercp_avatar_upload.html',
        'usercp_avatar_remote' => __DIR__ . '/templates/usercp_avatar_remote.html',
        'usercp_avatar_remove' => __DIR__ . '/templates/usercp_avatar_remove.html',
        'usercp_avatar_auto_resize_auto' => __DIR__ . '/templates/usercp_avatar_auto_resize_auto.html',
        'usercp_avatar_auto_resize_user' => __DIR__ . '/templates/usercp_avatar_auto_resize_user.html',
        'usercp_editsig' => __DIR__ . '/templates/usercp_editsig.html',
        'usercp_editsig_current' => __DIR__ . '/templates/usercp_editsig_current.html',
        'usercp_editsig_preview' => __DIR__ . '/templates/usercp_editsig_preview.html',
        'usercp_editsig_suspended' => __DIR__ . '/templates/usercp_editsig_suspended.html',
        'usercp_options' => __DIR__ . '/templates/usercp_options.html',
        'usercp_options_invisible' => __DIR__ . '/templates/usercp_options_invisible.html',
        'usercp_options_date_format' => __DIR__ . '/templates/usercp_options_date_format.html',
        'usercp_options_language' => __DIR__ . '/templates/usercp_options_language.html',
        'usercp_options_language_option' => __DIR__ . '/templates/usercp_options_language_option.html',
        'usercp_options_pms' => __DIR__ . '/templates/usercp_options_pms.html',
        'usercp_options_pms_from_buddys' => __DIR__ . '/templates/usercp_options_pms_from_buddys.html',
        'usercp_options_pppselect' => __DIR__ . '/templates/usercp_options_pppselect.html',
        'usercp_options_pppselect_option' => __DIR__ . '/templates/usercp_options_pppselect_option.html',
        'usercp_options_quick_reply' => __DIR__ . '/templates/usercp_options_quick_reply.html',
        'usercp_options_style' => __DIR__ . '/templates/usercp_options_style.html',
        'usercp_options_time_format' => __DIR__ . '/templates/usercp_options_time_format.html',
        'usercp_options_timezone' => __DIR__ . '/templates/usercp_options_timezone.html',
        'usercp_options_timezone_option' => __DIR__ . '/templates/usercp_options_timezone_option.html',
        'usercp_options_tppselect' => __DIR__ . '/templates/usercp_options_tppselect.html',
        'usercp_options_tppselect_option' => __DIR__ . '/templates/usercp_options_tppselect_option.html',
        'usercp_themeselector' => __DIR__ . '/templates/usercp_themeselector.html',
        'usercp_themeselector_option' => __DIR__ . '/templates/usercp_themeselector_option.html',
        'usercp_password' => __DIR__ . '/templates/usercp_password.html',
        'usercp_email' => __DIR__ . '/templates/usercp_email.html',
        'usercp_changename' => __DIR__ . '/templates/usercp_changename.html',
        'usercp_editlists' => __DIR__ . '/templates/usercp_editlists.html',
        'usercp_editlists_user' => __DIR__ . '/templates/usercp_editlists_user.html',
        'usercp_editlists_no_buddies' => __DIR__ . '/templates/usercp_editlists_no_buddies.html',
        'usercp_editlists_no_ignored' => __DIR__ . '/templates/usercp_editlists_no_ignored.html',
        'usercp_editlists_received_requests' => __DIR__ . '/templates/usercp_editlists_received_requests.html',
        'usercp_editlists_received_request' => __DIR__ . '/templates/usercp_editlists_received_request.html',
        'usercp_editlists_sent_requests' => __DIR__ . '/templates/usercp_editlists_sent_requests.html',
        'usercp_editlists_sent_request' => __DIR__ . '/templates/usercp_editlists_sent_request.html',
        'usercp_editlists_no_requests' => __DIR__ . '/templates/usercp_editlists_no_requests.html',
        'usercp_usergroups' => __DIR__ . '/templates/usercp_usergroups.html',
        'usercp_usergroups_joingroup' => __DIR__ . '/templates/usercp_usergroups_joingroup.html',
        'usercp_usergroups_leader' => __DIR__ . '/templates/usercp_usergroups_leader.html',
        'usercp_usergroups_leader_usergroup' => __DIR__ . '/templates/usercp_usergroups_leader_usergroup.html',
        'usercp_usergroups_leader_usergroup_memberlist' => __DIR__ . '/templates/usercp_usergroups_leader_usergroup_memberlist.html',
        'usercp_usergroups_leader_usergroup_moderaterequests' => __DIR__ . '/templates/usercp_usergroups_leader_usergroup_moderaterequests.html',
        'usercp_usergroups_memberof' => __DIR__ . '/templates/usercp_usergroups_memberof.html',
        'usercp_usergroups_memberof_usergroup' => __DIR__ . '/templates/usercp_usergroups_memberof_usergroup.html',
        'usercp_usergroups_memberof_usergroup_description' => __DIR__ . '/templates/usercp_usergroups_memberof_usergroup_description.html',
        'usercp_usergroups_memberof_usergroup_display' => __DIR__ . '/templates/usercp_usergroups_memberof_usergroup_display.html',
        'usercp_usergroups_memberof_usergroup_leave' => __DIR__ . '/templates/usercp_usergroups_memberof_usergroup_leave.html',
        'usercp_usergroups_memberof_usergroup_leaveleader' => __DIR__ . '/templates/usercp_usergroups_memberof_usergroup_leaveleader.html',
        'usercp_usergroups_memberof_usergroup_leaveother' => __DIR__ . '/templates/usercp_usergroups_memberof_usergroup_leaveother.html',
        'usercp_usergroups_memberof_usergroup_leaveprimary' => __DIR__ . '/templates/usercp_usergroups_memberof_usergroup_leaveprimary.html',
        'usercp_usergroups_memberof_usergroup_setdisplay' => __DIR__ . '/templates/usercp_usergroups_memberof_usergroup_setdisplay.html',
        'usercp_usergroups_joinable' => __DIR__ . '/templates/usercp_usergroups_joinable.html',
        'usercp_usergroups_joinable_usergroup' => __DIR__ . '/templates/usercp_usergroups_joinable_usergroup.html',
        'usercp_usergroups_joinable_usergroup_description' => __DIR__ . '/templates/usercp_usergroups_joinable_usergroup_description.html',
        'usercp_usergroups_joinable_usergroup_join' => __DIR__ . '/templates/usercp_usergroups_joinable_usergroup_join.html',
        'usercp_subscriptions' => __DIR__ . '/templates/usercp_subscriptions.html',
        'usercp_subscriptions_thread' => __DIR__ . '/templates/usercp_subscriptions_thread.html',
        'usercp_subscriptions_thread_icon' => __DIR__ . '/templates/usercp_subscriptions_thread_icon.html',
        'usercp_subscriptions_remove' => __DIR__ . '/templates/usercp_subscriptions_remove.html',
        'usercp_subscriptions_none' => __DIR__ . '/templates/usercp_subscriptions_none.html',
        'usercp_forumsubscriptions' => __DIR__ . '/templates/usercp_forumsubscriptions.html',
        'usercp_forumsubscriptions_forum' => __DIR__ . '/templates/usercp_forumsubscriptions_forum.html',
        'usercp_forumsubscriptions_none' => __DIR__ . '/templates/usercp_forumsubscriptions_none.html',
        'usercp_addsubscription_thread' => __DIR__ . '/templates/usercp_addsubscription_thread.html',
        'usercp_removesubscription_thread' => __DIR__ . '/templates/usercp_removesubscription_thread.html',
        'usercp_removesubscription_forum' => __DIR__ . '/templates/usercp_removesubscription_forum.html',
        'usercp_drafts' => __DIR__ . '/templates/usercp_drafts.html',
        'usercp_drafts_draft' => __DIR__ . '/templates/usercp_drafts_draft.html',
        'usercp_drafts_draft_forum' => __DIR__ . '/templates/usercp_drafts_draft_forum.html',
        'usercp_drafts_draft_thread' => __DIR__ . '/templates/usercp_drafts_draft_thread.html',
        'usercp_drafts_none' => __DIR__ . '/templates/usercp_drafts_none.html',
        'usercp_attachments' => __DIR__ . '/templates/usercp_attachments.html',
        'usercp_attachments_attachment' => __DIR__ . '/templates/usercp_attachments_attachment.html',
        'usercp_attachments_none' => __DIR__ . '/templates/usercp_attachments_none.html',
        'delete_attachments_button' => __DIR__ . '/templates/delete_attachments_button.html',
        // MyBB 1.8.40 posting routes share this semantic compose shell and
        // its layout-bearing option, icon, poll and attachment fragments.
        'newthread' => __DIR__ . '/templates/newthread.html',
        'newreply' => __DIR__ . '/templates/newreply.html',
        'editpost' => __DIR__ . '/templates/editpost.html',
        'newthread_postoptions' => __DIR__ . '/templates/newthread_postoptions.html',
        'newreply_postoptions' => __DIR__ . '/templates/newreply_postoptions.html',
        'editpost_postoptions' => __DIR__ . '/templates/editpost_postoptions.html',
        'editpost_reason' => __DIR__ . '/templates/editpost_reason.html',
        'newreply_modoptions' => __DIR__ . '/templates/newreply_modoptions.html',
        'newthread_postpoll' => __DIR__ . '/templates/newthread_postpoll.html',
        'post_subscription_method' => __DIR__ . '/templates/post_subscription_method.html',
        'posticons' => __DIR__ . '/templates/posticons.html',
        'posticons_icon' => __DIR__ . '/templates/posticons_icon.html',
        'post_attachments' => __DIR__ . '/templates/post_attachments.html',
        'post_attachments_new' => __DIR__ . '/templates/post_attachments_new.html',
        'post_attachments_attachment' => __DIR__ . '/templates/post_attachments_attachment.html',
        'post_attachments_attachment_unapproved' => __DIR__ . '/templates/post_attachments_attachment_unapproved.html',
        'editpost_delete' => __DIR__ . '/templates/editpost_delete.html',
        'showthread' => __DIR__ . '/templates/showthread.html',
        'showthread_quickreply' => __DIR__ . '/templates/showthread_quickreply.html',
        // moderation.php keeps MyBB's controller, permissions and POST contracts,
        // while ATF owns the common full-page presentation roots.
        'moderation_move' => __DIR__ . '/templates/moderation_move.html',
        'moderation_inline_movethreads' => __DIR__ . '/templates/moderation_inline_movethreads.html',
        'moderation_deletethread' => __DIR__ . '/templates/moderation_deletethread.html',
        'moderation_deletepoll' => __DIR__ . '/templates/moderation_deletepoll.html',
        'moderation_confirmation' => __DIR__ . '/templates/moderation_confirmation.html',
        'moderation_merge' => __DIR__ . '/templates/moderation_merge.html',
        'moderation_inline_deleteposts' => __DIR__ . '/templates/moderation_inline_deleteposts.html',
        'moderation_inline_deletethreads' => __DIR__ . '/templates/moderation_inline_deletethreads.html',
        'moderation_inline_mergeposts' => __DIR__ . '/templates/moderation_inline_mergeposts.html',
        'moderation_inline_splitposts' => __DIR__ . '/templates/moderation_inline_splitposts.html',
        'moderation_inline_moveposts' => __DIR__ . '/templates/moderation_inline_moveposts.html',
        'moderation_split' => __DIR__ . '/templates/moderation_split.html',
        'moderation_purgespammer' => __DIR__ . '/templates/moderation_purgespammer.html',
        'moderation_getip' => __DIR__ . '/templates/moderation_getip.html',
        'moderation_threadnotes' => __DIR__ . '/templates/moderation_threadnotes.html',
        'multipage' => __DIR__ . '/templates/multipage.html',
        'postbit_classic' => __DIR__ . '/templates/postbit_classic.html',
        'private' => __DIR__ . '/templates/private.html',
        'private_messagebit' => __DIR__ . '/templates/private_messagebit.html',
        'private_messagebit_icon' => __DIR__ . '/templates/private_messagebit_icon.html',
        'private_messagebit_denyreceipt' => __DIR__ . '/templates/private_messagebit_denyreceipt.html',
        'private_multiple_recipients' => __DIR__ . '/templates/private_multiple_recipients.html',
        'private_multiple_recipients_user' => __DIR__ . '/templates/private_multiple_recipients_user.html',
        'private_multiple_recipients_bcc' => __DIR__ . '/templates/private_multiple_recipients_bcc.html',
        'private_jump_folders' => __DIR__ . '/templates/private_jump_folders.html',
        'private_jump_folders_folder' => __DIR__ . '/templates/private_jump_folders_folder.html',
        'private_move' => __DIR__ . '/templates/private_move.html',
        'private_orderarrow' => __DIR__ . '/templates/private_orderarrow.html',
        'private_pmspace' => __DIR__ . '/templates/private_pmspace.html',
        'private_composelink' => __DIR__ . '/templates/private_composelink.html',
        'private_emptyexportlink' => __DIR__ . '/templates/private_emptyexportlink.html',
        'private_limitwarning' => __DIR__ . '/templates/private_limitwarning.html',
        'private_nomessages' => __DIR__ . '/templates/private_nomessages.html',
        'private_advanced_search' => __DIR__ . '/templates/private_advanced_search.html',
        'private_advanced_search_folders' => __DIR__ . '/templates/private_advanced_search_folders.html',
        'private_search_results' => __DIR__ . '/templates/private_search_results.html',
        'private_search_messagebit' => __DIR__ . '/templates/private_search_messagebit.html',
        'private_search_results_nomessages' => __DIR__ . '/templates/private_search_results_nomessages.html',
        'private_read' => __DIR__ . '/templates/private_read.html',
        'private_read_action' => __DIR__ . '/templates/private_read_action.html',
        'private_read_to' => __DIR__ . '/templates/private_read_to.html',
        'private_read_bcc' => __DIR__ . '/templates/private_read_bcc.html',
        'private_quickreply' => __DIR__ . '/templates/private_quickreply.html',
        'private_send' => __DIR__ . '/templates/private_send.html',
        'private_send_autocomplete' => __DIR__ . '/templates/private_send_autocomplete.html',
        'private_send_buddyselect' => __DIR__ . '/templates/private_send_buddyselect.html',
        'private_send_tracking' => __DIR__ . '/templates/private_send_tracking.html',
        'private_tracking' => __DIR__ . '/templates/private_tracking.html',
        'private_tracking_nomessage' => __DIR__ . '/templates/private_tracking_nomessage.html',
        'private_tracking_readmessage' => __DIR__ . '/templates/private_tracking_readmessage.html',
        'private_tracking_unreadmessage' => __DIR__ . '/templates/private_tracking_unreadmessage.html',
        'private_tracking_readmessage_stop' => __DIR__ . '/templates/private_tracking_readmessage_stop.html',
        'private_tracking_unreadmessage_stop' => __DIR__ . '/templates/private_tracking_unreadmessage_stop.html',
        'private_folders' => __DIR__ . '/templates/private_folders.html',
        'private_folders_folder' => __DIR__ . '/templates/private_folders_folder.html',
        'private_folders_folder_unremovable' => __DIR__ . '/templates/private_folders_folder_unremovable.html',
        'private_empty' => __DIR__ . '/templates/private_empty.html',
        'private_empty_folder' => __DIR__ . '/templates/private_empty_folder.html',
        'private_archive' => __DIR__ . '/templates/private_archive.html',
        'private_archive_folders' => __DIR__ . '/templates/private_archive_folders.html',
        'private_archive_folders_folder' => __DIR__ . '/templates/private_archive_folders_folder.html',
    ];
}

/**
 * While enabled, providers must leave every catalogue template alone, including
 * manual_override/restore_conflict rows. The existing lease ledger remains the
 * authority for acquisition, upgrades and restoration; this API never writes it.
 */
function af_adaptivethemeframework_reserves_template(string $templateName): bool
{
    return function_exists('af_is_addon_enabled')
        && af_is_addon_enabled('adaptivethemeframework')
        && array_key_exists($templateName, af_adaptivethemeframework_template_seeds());
}
