<?php
/**
 * AF AAS userlist alias (AUTO-GENERATED FILE)
 * Generated by Advanced Account Switcher addon.
 * Source template: /inc/plugins/advancedfunctionality/addons/advancedaccountswitcher/assets/userlist.php
 * Marker: AF_AAS_USERLIST_ALIAS
 */

define('IN_MYBB', 1);
define('THIS_SCRIPT', 'userlist.php');

require_once __DIR__ . '/global.php';

if (!function_exists('af_aas_render_account_list_page')) {
    // Фоллбек: хотя бы не роняем сайт, уйдём на старый маршрут
    $bburl = rtrim((string)($mybb->settings['bburl'] ?? ''), '/');
    if ($bburl !== '') {
        header('Location: ' . $bburl . '/misc.php?action=af_aas_account_list');
        exit;
    }
    error_no_permission();
}

af_aas_render_account_list_page();
