<?php
/**
 * AF Addon Manifest: CharacterSheets
 * MyBB 1.8.x, PHP 8.0–8.4
 */

return [
    'id'          => 'charactersheets',
    'name'        => 'CharacterSheets',
    'description' => 'Автопринятие анкет, перенос в архив и триггер листа персонажа.',
    'version'     => '1.0.0',
    'author'      => 'CaptainPaws',
    'website'     => 'https://github.com/CaptainPaws',
    'bootstrap'   => 'charactersheets.php',

    // Если у аддона будет AF-страница в ACP через роутер:
    // (если admin.php реально отсутствует — можешь удалить этот блок целиком)
    'admin' => [
        'slug'       => 'charactersheets',
        'name'       => 'CharacterSheets',
        'controller' => 'admin.php',
    ],

    /**
     * Языковые пакеты генерируются ядром AF по этим ключам.
     * Канон: russian/english + секции front/admin без _ru/_en суффиксов.
     */
    'lang' => [
        'russian' => [
            'front' => [
                'af_charactersheets_name'              => 'CharacterSheets',
                'af_charactersheets_description'       => 'Автопринятие анкет и триггер листов персонажей.',
                'af_charactersheets_accept_button'     => 'Принять анкету',
                'af_charactersheets_kb_button'         => 'Создать запись в KB',
                'af_charactersheets_kb_sync_button'    => 'Синхронизировать анкету → KB',
                'af_charactersheets_create_sheet_button'=> 'Создать лист персонажа',
                'af_charactersheets_accept_done'       => 'Анкета принята: тема закрыта и перенесена.',
                'af_charactersheets_kb_create_done'    => 'KB-запись персонажа создана.',
                'af_charactersheets_kb_create_exists'  => 'KB-запись уже существовала, связь обновлена.',
                'af_charactersheets_kb_create_error'   => 'Не удалось создать запись KB.',
                'af_charactersheets_kb_sync_done'      => 'KB-запись синхронизирована с анкетой.',
                'af_charactersheets_kb_sync_error'     => 'Не удалось синхронизировать KB-запись.',
                'af_charactersheets_sheet_create_done' => 'Лист персонажа создан.',
                'af_charactersheets_sheet_create_exists' => 'Лист персонажа уже существует.',
                'af_charactersheets_sheet_create_error' => 'Не удалось создать лист персонажа.',
                'af_charactersheets_sheet_requires_kb' => 'Сначала создайте или привяжите KB-запись персонажа.',
                'af_charactersheets_accept_already'    => 'Анкета уже была принята.',
                'af_charactersheets_accept_error'      => 'Не удалось принять анкету. Обратитесь к администратору.',
                'af_charactersheets_accept_no_permission' => 'У вас нет прав для принятия анкеты.',
                'af_charactersheets_accept_invalid_thread' => 'Тема не найдена или недоступна.',
                'af_charactersheets_sheet_button'      => 'Лист персонажа',
                'af_charactersheets_sheet_modal_title' => 'Лист персонажа',
                'af_charactersheets_sheet_modal_close' => 'Закрыть',
                'af_charactersheets_mechanics_title'   => 'Механика',
                'af_charactersheets_mech_ac'           => 'Класс брони',
                'af_charactersheets_mech_saves'        => 'Спасброски',
                'af_charactersheets_mech_fortitude'    => 'Стойкость / Fortitude',
                'af_charactersheets_mech_reflex'       => 'Рефлекс / Reflex',
                'af_charactersheets_mech_will'         => 'Воля / Will',
                'af_charactersheets_mech_perception'   => 'Восприятие / Perception',
                'af_charactersheets_mech_damage'       => 'Урон',
                'af_charactersheets_mech_speed'        => 'Скорость',
                'af_charactersheets_mech_hp'           => 'Здоровье',
            ],
            'admin' => [
                'af_charactersheets_group'                   => 'AF: CharacterSheets',
                'af_charactersheets_group_desc'              => 'Автопринятие анкет, перенос и триггер листов персонажей.',

                'af_charactersheets_enabled'                 => 'Включить CharacterSheets',
                'af_charactersheets_enabled_desc'            => 'Включает кнопку принятия анкеты и обработчик misc.php.',

                'af_charactersheets_accept_groups'           => 'Группы, которым доступно принятие',
                'af_charactersheets_accept_groups_desc'      => 'CSV id групп (usergroup/additionalgroups), которым доступна кнопка принятия анкеты. Пример: 4,3,6',

                'af_charactersheets_pending_forums'          => 'Форумы ожидания анкет',
                'af_charactersheets_pending_forums_desc'     => 'CSV fid форумов, где анкеты считаются ожидающими. Пример: 12,13,14',

                'af_charactersheets_accepted_forum'          => 'Форум принятых анкет',
                'af_charactersheets_accepted_forum_desc'     => 'fid форума, куда переносить принятые анкеты.',

                'af_charactersheets_accept_wrap_htmlbb'      => 'Оборачивать сообщение в [html][/html]',
                'af_charactersheets_accept_wrap_htmlbb_desc' => 'Если включено, текст принятия будет обёрнут в [html]...[/html].',

                'af_charactersheets_accept_close_thread'     => 'Закрывать тему после принятия',
                'af_charactersheets_accept_close_thread_desc'=> 'Если включено, тема будет закрыта.',

                'af_charactersheets_accept_move_thread'      => 'Переносить тему после принятия',
                'af_charactersheets_accept_move_thread_desc' => 'Если включено, тема будет перенесена в форум принятых анкет.',

                'af_charactersheets_sheet_autocreate'        => 'Автосоздание листа персонажа',
                'af_charactersheets_sheet_autocreate_desc'   => 'Если включено, после принятия срабатывает генератор листа персонажа (заглушка).',
                'af_charactersheets_render_path_mode'         => 'Render path листа',
                'af_charactersheets_render_path_mode_desc'    => 'auto — автоопределение профиля, dnd/arpg — принудительный выбор шаблона.',
                'af_cs_assets_blacklist'                 => 'Blacklist ассетов CharacterSheets',
                'af_cs_assets_blacklist_desc'            => "Одна строка = одно правило: script.php или script.php?action=... . На указанных страницах не подключаются charactersheets.css/js.",
                'af_charactersheets_exp_per_char'            => 'EXP за символ',
                'af_charactersheets_exp_per_char_desc'       => 'Опыт начисляется за символ в посте.',
                'af_charactersheets_exp_forum_categories'    => 'EXP: категории форумов',
                'af_charactersheets_exp_forum_categories_desc' => 'CSV fid категорий. Учитываются все дочерние форумы.',
                'af_charactersheets_exp_forum_forums'        => 'EXP: отдельные форумы',
                'af_charactersheets_exp_forum_forums_desc'   => 'CSV fid форумов, где начислять опыт.',
                'af_charactersheets_exp_forum_exclude'       => 'EXP: исключения',
                'af_charactersheets_exp_forum_exclude_desc'  => 'CSV fid форумов, где опыт не начисляется.',
                'af_charactersheets_exp_forum_mode'          => 'EXP: режим выбора',
                'af_charactersheets_exp_forum_mode_desc'     => 'include = только выбранные, exclude = всё кроме выбранных.',
                'af_charactersheets_exp_allow_negative'      => 'Разрешить отрицательное начисление EXP',
                'af_charactersheets_exp_allow_negative_desc' => 'Если включено, можно списывать опыт вручную.',
                'af_charactersheets_exp_allow_overdraw'      => 'Разрешить уход EXP в минус',
                'af_charactersheets_exp_allow_overdraw_desc' => 'Если выключено, EXP не опускается ниже нуля.',
                'af_charactersheets_skill_points_per_level'  => 'Очки навыков за уровень',
                'af_charactersheets_skill_points_per_level_desc' => 'Сколько очков навыков выдаётся за уровень.',
                'af_cs_skill_ranks_json'                     => 'Ранги навыков (JSON)',
                'af_cs_skill_ranks_json_desc'                => 'JSON-конфиг рангов 0..5: title_ru/title_en + bonus.',
                'af_charactersheets_knowledge_base_choices'   => 'Базовые выборы знаний',
                'af_charactersheets_knowledge_base_choices_desc' => 'Базовое количество выборов знаний.',
                'af_charactersheets_knowledge_per_int'        => 'Знания за INT',
                'af_charactersheets_knowledge_per_int_desc'   => 'Сколько выборов добавляется за 1 INT (floor).',
                'af_charactersheets_aug_slots_json'           => 'Слоты аугментаций',
                'af_charactersheets_aug_slots_json_desc'      => 'JSON список слотов: slot_key, title_ru/title_en, icon, sortorder, max_equipped.',
                'af_charactersheets_staff_groups'             => 'Группы staff для сброса',
                'af_charactersheets_staff_groups_desc'        => 'CSV id групп, которым доступен сброс атрибутов/навыков.',
                'af_charactersheets_exp_manual_groups'        => 'Группы ручного начисления EXP',
                'af_charactersheets_exp_manual_groups_desc'   => 'CSV id групп, которые могут выдавать EXP вручную.',

                'af_charactersheets_admin_title'             => 'CharacterSheets',
                'af_charactersheets_admin_subtitle'          => 'Настройка текста принятия анкеты.',
                'af_charactersheets_admin_accept_template'   => 'Текст сообщения принятия',
                'af_charactersheets_admin_accept_template_desc' => 'Плейсхолдеры: {mention}, {username}, {uid}, {thread_url}, {profile_url}, {accepted_by}, {sheet_url}, {sheet_slug}.',
                'af_charactersheets_admin_save'              => 'Сохранить',
                'af_charactersheets_admin_saved'             => 'Настройки сохранены.',
                'af_charactersheets_admin_skills'            => 'Навыки',
                'af_charactersheets_admin_skills_list'       => 'Список навыков',
                'af_charactersheets_admin_skill_saved'       => 'Навык сохранён.',
                'af_charactersheets_admin_skill_deleted'     => 'Навык удалён.',
                'af_charactersheets_admin_skill_slug_invalid'=> 'Некорректный ключ навыка.',
                'af_charactersheets_admin_skill_title_invalid'=> 'Укажите название навыка.',
                'af_charactersheets_admin_skill_attr_invalid'=> 'Некорректный атрибут.',
                'af_charactersheets_admin_back'              => 'Назад',
                'af_charactersheets_admin_skill_ranks'       => 'Ранги навыков',
                'af_charactersheets_admin_skill_ranks_saved' => 'Ранги навыков сохранены.',
                'af_charactersheets_admin_skill_ranks_invalid' => 'Некорректные данные рангов.',
            ],
        ],

        'english' => [
            'front' => [
                'af_charactersheets_name'              => 'CharacterSheets',
                'af_charactersheets_description'       => 'Auto-accept applications and trigger character sheets.',
                'af_charactersheets_accept_button'     => 'Accept application',
                'af_charactersheets_kb_button'         => 'Create KB entry',
                'af_charactersheets_kb_sync_button'    => 'Sync application → KB',
                'af_charactersheets_create_sheet_button'=> 'Create character sheet',
                'af_charactersheets_accept_done'       => 'Application accepted: thread closed and moved.',
                'af_charactersheets_kb_create_done'    => 'Character KB entry created.',
                'af_charactersheets_kb_create_exists'  => 'KB entry already existed, link refreshed.',
                'af_charactersheets_kb_create_error'   => 'Failed to create KB entry.',
                'af_charactersheets_kb_sync_done'      => 'KB entry synced from application.',
                'af_charactersheets_kb_sync_error'     => 'Failed to sync KB entry.',
                'af_charactersheets_sheet_create_done' => 'Character sheet created.',
                'af_charactersheets_sheet_create_exists' => 'Character sheet already exists.',
                'af_charactersheets_sheet_create_error' => 'Failed to create character sheet.',
                'af_charactersheets_sheet_requires_kb' => 'Create or link the character KB entry first.',
                'af_charactersheets_accept_already'    => 'Application has already been accepted.',
                'af_charactersheets_accept_error'      => 'Failed to accept the application. Contact an administrator.',
                'af_charactersheets_accept_no_permission' => 'You do not have permission to accept this application.',
                'af_charactersheets_accept_invalid_thread' => 'Thread not found or not accessible.',
                'af_charactersheets_sheet_button'      => 'Character sheet',
                'af_charactersheets_sheet_modal_title' => 'Character sheet',
                'af_charactersheets_sheet_modal_close' => 'Close',
                'af_charactersheets_mechanics_title'   => 'Mechanics',
                'af_charactersheets_mech_ac'           => 'Armor Class',
                'af_charactersheets_mech_saves'        => 'Saving Throws',
                'af_charactersheets_mech_fortitude'    => 'Fortitude',
                'af_charactersheets_mech_reflex'       => 'Reflex',
                'af_charactersheets_mech_will'         => 'Will',
                'af_charactersheets_mech_perception'   => 'Perception',
                'af_charactersheets_mech_damage'       => 'Damage',
                'af_charactersheets_mech_speed'        => 'Speed',
                'af_charactersheets_mech_hp'           => 'Health',
            ],
            'admin' => [
                'af_charactersheets_group'                   => 'AF: CharacterSheets',
                'af_charactersheets_group_desc'              => 'CharacterSheets addon settings.',

                'af_charactersheets_enabled'                 => 'Enable CharacterSheets',
                'af_charactersheets_enabled_desc'            => 'Enables the accept button and misc.php handler.',

                'af_charactersheets_accept_groups'           => 'Groups allowed to accept',
                'af_charactersheets_accept_groups_desc'      => 'CSV group ids (usergroup/additionalgroups) allowed to accept. Example: 4,3,6',

                'af_charactersheets_pending_forums'          => 'Pending application forums',
                'af_charactersheets_pending_forums_desc'     => 'CSV forum ids where applications are pending. Example: 12,13,14',

                'af_charactersheets_accepted_forum'          => 'Accepted applications forum',
                'af_charactersheets_accepted_forum_desc'     => 'Forum id to move accepted applications into.',

                'af_charactersheets_accept_wrap_htmlbb'      => 'Wrap acceptance post in [html][/html]',
                'af_charactersheets_accept_wrap_htmlbb_desc' => 'If enabled, the acceptance text is wrapped in [html]...[/html].',

                'af_charactersheets_accept_close_thread'     => 'Close thread after acceptance',
                'af_charactersheets_accept_close_thread_desc'=> 'If enabled, the thread will be closed.',

                'af_charactersheets_accept_move_thread'      => 'Move thread after acceptance',
                'af_charactersheets_accept_move_thread_desc' => 'If enabled, the thread will be moved to the accepted forum.',

                'af_charactersheets_sheet_autocreate'        => 'Auto-create character sheet',
                'af_charactersheets_sheet_autocreate_desc'   => 'If enabled, triggers the character sheet generator (stub).',
                'af_charactersheets_render_path_mode'         => 'Sheet render path',
                'af_charactersheets_render_path_mode_desc'    => 'auto = detect by profile; dnd/arpg = force selected template path.',
                'af_cs_assets_blacklist'                 => 'CharacterSheets assets blacklist',
                'af_cs_assets_blacklist_desc'            => 'One rule per line: script.php or script.php?action=... . CharacterSheets CSS/JS will not be included on matched pages.',
                'af_charactersheets_exp_per_char'            => 'EXP per character',
                'af_charactersheets_exp_per_char_desc'       => 'Experience granted per post character.',
                'af_charactersheets_exp_forum_categories'    => 'EXP forums: categories',
                'af_charactersheets_exp_forum_categories_desc' => 'CSV category fids. Includes child forums.',
                'af_charactersheets_exp_forum_forums'        => 'EXP forums: forums',
                'af_charactersheets_exp_forum_forums_desc'   => 'CSV forum fids included.',
                'af_charactersheets_exp_forum_exclude'       => 'EXP forums: exclude',
                'af_charactersheets_exp_forum_exclude_desc'  => 'CSV forum fids excluded.',
                'af_charactersheets_exp_forum_mode'          => 'EXP forums: mode',
                'af_charactersheets_exp_forum_mode_desc'     => 'include = only selected, exclude = all except selected.',
                'af_charactersheets_exp_allow_negative'      => 'Allow negative EXP awards',
                'af_charactersheets_exp_allow_negative_desc' => 'Allow manual EXP subtraction.',
                'af_charactersheets_exp_allow_overdraw'      => 'Allow EXP to go below zero',
                'af_charactersheets_exp_allow_overdraw_desc' => 'If disabled, EXP cannot drop below zero.',
                'af_charactersheets_skill_points_per_level'  => 'Skill points per level',
                'af_charactersheets_skill_points_per_level_desc' => 'Skill points granted on each level up.',
                'af_cs_skill_ranks_json'                     => 'Skill ranks (JSON)',
                'af_cs_skill_ranks_json_desc'                => 'JSON config for ranks 0..5: title_ru/title_en + bonus.',
                'af_charactersheets_knowledge_base_choices'  => 'Knowledge base choices',
                'af_charactersheets_knowledge_base_choices_desc' => 'Base number of knowledge choices.',
                'af_charactersheets_knowledge_per_int'       => 'Knowledge per INT',
                'af_charactersheets_knowledge_per_int_desc'  => 'Choices added per INT point (floor).',
                'af_charactersheets_aug_slots_json'          => 'Augmentation slots',
                'af_charactersheets_aug_slots_json_desc'     => 'JSON list of slots: slot_key, title_ru/title_en, icon, sortorder, max_equipped.',
                'af_charactersheets_staff_groups'            => 'Staff reset groups',
                'af_charactersheets_staff_groups_desc'       => 'CSV group ids allowed to reset attributes/skills.',
                'af_charactersheets_exp_manual_groups'       => 'EXP manual award groups',
                'af_charactersheets_exp_manual_groups_desc'  => 'CSV group ids allowed to grant experience manually.',

                'af_charactersheets_admin_title'             => 'CharacterSheets',
                'af_charactersheets_admin_subtitle'          => 'Acceptance message template settings.',
                'af_charactersheets_admin_accept_template'   => 'Acceptance message',
                'af_charactersheets_admin_accept_template_desc' => 'Placeholders: {mention}, {username}, {uid}, {thread_url}, {profile_url}, {accepted_by}, {sheet_url}, {sheet_slug}.',
                'af_charactersheets_admin_save'              => 'Save',
                'af_charactersheets_admin_saved'             => 'Settings saved.',
                'af_charactersheets_admin_skills'            => 'Skills',
                'af_charactersheets_admin_skills_list'       => 'Skills list',
                'af_charactersheets_admin_skill_saved'       => 'Skill saved.',
                'af_charactersheets_admin_skill_deleted'     => 'Skill deleted.',
                'af_charactersheets_admin_skill_slug_invalid'=> 'Invalid skill slug.',
                'af_charactersheets_admin_skill_title_invalid'=> 'Provide a skill title.',
                'af_charactersheets_admin_skill_attr_invalid'=> 'Invalid attribute.',
                'af_charactersheets_admin_back'              => 'Back',
                'af_charactersheets_admin_skill_ranks'       => 'Skill ranks',
                'af_charactersheets_admin_skill_ranks_saved' => 'Skill ranks saved.',
                'af_charactersheets_admin_skill_ranks_invalid' => 'Invalid skill ranks payload.',
            ],
        ],
    ],
];
