<?php
return [
    'id'          => 'advancedshop',
    'name'        => 'Advanced Shop',
    'author'      => 'CaptainPaws',
    'authorsite'  => 'https://github.com/CaptainPaws',
    'description' => 'Game shop and inventory for AdvancedFunctionality.',
    'version'     => '1.0.0',
    'bootstrap'   => 'advancedshop.php',
    'lang' => [
        'russian' => [
            'front' => [
                'af_advancedshop_name' => 'Магазин',
                'af_advancedshop_description' => 'Игровой магазин и инвентарь.',
                'af_advancedshop_shop_title' => 'Магазин',
                'af_advancedshop_cart_title' => 'Корзина',
                'af_advancedshop_inventory_title' => 'Инвентарь',
                'af_advancedshop_manage_title' => 'Управление магазином',
                'af_advancedshop_btn_buy' => 'Купить',
                'af_advancedshop_btn_add_to_cart' => 'В корзину',
                'af_advancedshop_btn_go_to_cart' => 'К корзине',
                'af_advancedshop_btn_checkout' => 'Оформить',
                'af_advancedshop_balance' => 'Баланс',
                'af_advancedshop_total' => 'Итого',
                'af_advancedshop_empty_cart' => 'Корзина пуста',
                'af_advancedshop_error_not_enough_money' => 'Недостаточно средств',
                'af_advancedshop_error_not_allowed' => 'Недостаточно прав',
                'af_advancedshop_success_checkout' => 'Покупка оформлена',
                'af_advancedshop_back_to_shop' => 'Назад в магазин',
                'af_advancedshop_rarity_label' => 'Редкость',
                'af_advancedshop_rarity_common' => 'Обычная',
                'af_advancedshop_rarity_uncommon' => 'Необычная',
                'af_advancedshop_rarity_rare' => 'Редкая',
                                'af_advancedshop_rarity_unique' => 'Уникальная',
                'af_advancedshop_rarity_illegal' => 'Незаконная',
                'af_advancedshop_rarity_restricted' => 'Ограниченная',
                'af_advancedshop_rarity_legendary' => 'Легендарная',
                'af_advancedshop_rarity_mythic' => 'Мифическая',
                'af_advancedshop_rarity_unknown' => '—',
            ],
            'admin' => [
                'af_advancedshop_group' => 'AF: Магазин',
                'af_advancedshop_group_desc' => 'Настройки внутреннего аддона магазина.',
                'af_advancedshop_enabled' => 'Включить магазин',
                'af_advancedshop_enabled_desc' => 'Да/Нет',
                'af_advancedshop_manage_groups' => 'Группы управления магазином',
                'af_advancedshop_manage_groups_desc' => 'ID групп через запятую.',
                'af_advancedshop_currency_slug' => 'Валюта',
                'af_advancedshop_currency_slug_desc' => 'Слаг валюты (по умолчанию credits).',
                'af_advancedshop_settings_saved' => 'Настройки сохранены',
            ],
        ],
        'english' => [
            'front' => [
                'af_advancedshop_name' => 'Shop',
                'af_advancedshop_description' => 'Game shop and inventory.',
                'af_advancedshop_shop_title' => 'Shop',
                'af_advancedshop_cart_title' => 'Cart',
                'af_advancedshop_inventory_title' => 'Inventory',
                'af_advancedshop_manage_title' => 'Manage Shop',
                'af_advancedshop_btn_buy' => 'Buy',
                'af_advancedshop_btn_add_to_cart' => 'Add to Cart',
                'af_advancedshop_btn_go_to_cart' => 'Go to Cart',
                'af_advancedshop_btn_checkout' => 'Checkout',
                'af_advancedshop_balance' => 'Balance',
                'af_advancedshop_total' => 'Total',
                'af_advancedshop_empty_cart' => 'Cart is empty',
                'af_advancedshop_error_not_enough_money' => 'Not enough money',
                'af_advancedshop_error_not_allowed' => 'Not allowed',
                'af_advancedshop_success_checkout' => 'Checkout successful',
                'af_advancedshop_back_to_shop' => 'Back to shop',
                'af_advancedshop_rarity_label' => 'Rarity',
                'af_advancedshop_rarity_common' => 'Common',
                'af_advancedshop_rarity_uncommon' => 'Uncommon',
                'af_advancedshop_rarity_rare' => 'Rare',
                                'af_advancedshop_rarity_unique' => 'Unique',
                'af_advancedshop_rarity_illegal' => 'Illegal',
                'af_advancedshop_rarity_restricted' => 'Restricted',
                'af_advancedshop_rarity_legendary' => 'Legendary',
                'af_advancedshop_rarity_mythic' => 'Mythic',
                'af_advancedshop_rarity_unknown' => '—',
            ],
            'admin' => [
                'af_advancedshop_group' => 'AF: Shop',
                'af_advancedshop_group_desc' => 'Internal addon shop settings.',
                'af_advancedshop_enabled' => 'Enable shop',
                'af_advancedshop_enabled_desc' => 'Yes/No',
                'af_advancedshop_manage_groups' => 'Manage groups',
                'af_advancedshop_manage_groups_desc' => 'Comma separated group IDs.',
                'af_advancedshop_currency_slug' => 'Currency slug',
                'af_advancedshop_currency_slug_desc' => 'Currency slug (default credits).',
                'af_advancedshop_settings_saved' => 'Settings saved',
            ],
        ],
    ],
    'admin' => [
        'slug' => 'advancedshop',
        'title' => 'Advanced Shop',
        'controller' => 'admin.php',
        'order' => 35,
    ],
];
