<?php

return [
    'id'          => 'advancedgallery',
    'name'        => 'Галерея',
    'description' => 'Пользовательская галерея изображений с загрузкой и модерацией.',
    'version'     => '1.0.0',
    'author'      => 'CaptainPaws',
    'website'     => 'https://github.com/CaptainPaws',

    'bootstrap'   => 'advancedgallery.php',

    'admin' => [
        'slug'       => 'advancedgallery',
        'name'       => 'Галерея',
        'controller' => 'admin.php',
    ],

    'lang' => [
        'front' => [
            'af_advancedgallery_name'        => 'Галерея',
            'af_advancedgallery_description' => 'Галерея изображений.',
            'af_advancedgallery_albums' => 'Альбомы',
            'af_advancedgallery_my_albums' => 'Мои альбомы',
            'af_advancedgallery_create_album' => 'Создать альбом',
            'af_advancedgallery_edit_album' => 'Редактировать альбом',
            'af_advancedgallery_delete_album' => 'Удалить альбом',
            'af_advancedgallery_album_title' => 'Название альбома',
            'af_advancedgallery_album_desc' => 'Описание',
            'af_advancedgallery_album_visibility' => 'Видимость',
            'af_advancedgallery_album_visibility_public' => 'Публичный',
            'af_advancedgallery_album_visibility_registered' => 'Только для зарегистрированных',
            'af_advancedgallery_album_visibility_private' => 'Приватный',
            'af_advancedgallery_album_visibility_groups' => 'По группам',
            'af_advancedgallery_album_allowed_groups' => 'Разрешённые группы (CSV)',
            'af_advancedgallery_album_sort_mode' => 'Сортировка',
            'af_advancedgallery_album_sort_manual' => 'Вручную',
            'af_advancedgallery_album_sort_date_desc' => 'Сначала новые',
            'af_advancedgallery_album_sort_date_asc' => 'Сначала старые',
            'af_advancedgallery_album_cover' => 'Обложка (ID медиа)',
            'af_advancedgallery_album_empty' => 'Нет содержимого.',
            'af_advancedgallery_album_saved' => 'Альбом сохранён.',
            'af_advancedgallery_album_deleted' => 'Альбом удалён.',
            'af_advancedgallery_added_to_album' => 'Добавить в альбом',
            'af_advancedgallery_removed_from_album' => 'Удалено из альбома.',
            'af_advancedgallery_limit_albums_reached' => 'Достигнут лимит альбомов.',
            'af_advancedgallery_limit_media_reached' => 'Достигнут лимит медиа в альбоме.',
        ],
        'admin' => [
            'af_advancedgallery_group'                   => 'Галерея',
            'af_advancedgallery_group_desc'              => 'Настройки галереи изображений.',
            'af_advancedgallery_enabled'                 => 'Включить галерею',
            'af_advancedgallery_items_per_page'          => 'Элементов на страницу',
            'af_advancedgallery_upload_max_mb'           => 'Макс. размер файла (МБ)',
            'af_advancedgallery_allowed_ext'             => 'Разрешённые расширения',
            'af_advancedgallery_thumb_w'                 => 'Ширина превью',
            'af_advancedgallery_thumb_h'                 => 'Высота превью',
            'af_advancedgallery_can_upload_groups'       => 'Группы с правом загрузки',
            'af_advancedgallery_can_moderate_groups'     => 'Группы модерации',
            'af_advancedgallery_autoapprove_groups'      => 'Группы автопринятия',
            'af_advancedgallery_max_albums' => 'Макс. альбомов на пользователя',
            'af_advancedgallery_max_albums_desc' => 'Макс. альбомов на пользователя (0 = без лимита).',
            'af_advancedgallery_max_media_per_album' => 'Макс. медиа в одном альбоме',
            'af_advancedgallery_max_media_per_album_desc' => 'Макс. медиа в одном альбоме (0 = без лимита).',
            'af_advancedgallery_album_visibility_default' => 'Видимость альбома по умолчанию',
            'af_advancedgallery_album_visibility_default_desc' => 'Видимость альбома по умолчанию.',
        ],
    ],
];
