<?php

return [
    'id'          => 'advancedgallery',
    'name'        => 'Галерея',
    'description' => 'Пользовательская галерея изображений с загрузкой и модерацией.',
    'version'     => '1.0.0',
    'author'      => 'CaptainPaws',
    'website'     => 'https://github.com/CaptainPaws',

    'bootstrap'   => 'advancedgallery.php',

    'admin' => [
        'slug'       => 'advancedgallery',
        'name'       => 'Галерея',
        'controller' => 'admin.php',
    ],

    'lang' => [
        'russian' => [
            'front' => [
                'af_advancedgallery_name'        => 'Галерея',
                'af_advancedgallery_description' => 'Галерея изображений.',
                'af_advancedgallery_albums' => 'Альбомы',
                'af_advancedgallery_my_albums' => 'Мои альбомы',
                'af_advancedgallery_create_album' => 'Создать альбом',
                'af_advancedgallery_edit_album' => 'Редактировать альбом',
                'af_advancedgallery_delete_album' => 'Удалить альбом',
                'af_advancedgallery_album_title' => 'Название альбома',
                'af_advancedgallery_album_desc' => 'Описание',
                'af_advancedgallery_album_visibility' => 'Видимость',
                'af_advancedgallery_album_visibility_public' => 'Публичный',
                'af_advancedgallery_album_visibility_registered' => 'Только для зарегистрированных',
                'af_advancedgallery_album_visibility_private' => 'Приватный',
                'af_advancedgallery_album_visibility_groups' => 'По группам',
                'af_advancedgallery_album_allowed_groups' => 'Разрешённые группы (CSV)',
                'af_advancedgallery_album_sort_mode' => 'Сортировка',
                'af_advancedgallery_album_sort_manual' => 'Вручную',
                'af_advancedgallery_album_sort_date_desc' => 'Сначала новые',
                'af_advancedgallery_album_sort_date_asc' => 'Сначала старые',
                'af_advancedgallery_album_cover' => 'Обложка (ID медиа)',
                'af_advancedgallery_album_empty' => 'Нет содержимого.',
                'af_advancedgallery_album_saved' => 'Альбом сохранён.',
                'af_advancedgallery_album_deleted' => 'Альбом удалён.',
                'af_advancedgallery_added_to_album' => 'Добавить в альбом',
                'af_advancedgallery_removed_from_album' => 'Удалено из альбома.',
                'af_advancedgallery_limit_albums_reached' => 'Достигнут лимит альбомов.',
                'af_advancedgallery_limit_media_reached' => 'Достигнут лимит медиа в альбоме.',
                'af_advancedgallery_remote_add' => 'Добавить по ссылке',
                'af_advancedgallery_remote_url' => 'Ссылка на медиа',
                'af_advancedgallery_remote_invalid_url' => 'Некорректный URL.',
                'af_advancedgallery_remote_domain_denied' => 'Домен запрещён.',
                'af_advancedgallery_remote_added' => 'Remote медиа добавлено.',
                'af_advancedgallery_remote_album_none' => 'Без альбома',
                'af_advancedgallery_picker_title' => 'Галерея',
                'af_advancedgallery_picker_insert_img' => 'Вставить IMG',
                'af_advancedgallery_picker_insert_link' => 'Вставить ссылкой',
                'af_advancedgallery_picker_upload_local' => 'Загрузить',
                'af_advancedgallery_picker_add_remote' => 'Добавить по ссылке',
                'af_advancedgallery_picker_media_tab' => 'Мои медиа',
                'af_advancedgallery_picker_albums_tab' => 'Мои альбомы',
                'af_advancedgallery_picker_search' => 'Поиск',
                'af_advancedgallery_picker_empty' => 'Нет медиа.',
            ],
            'admin' => [
                'af_advancedgallery_group'                   => 'Галерея',
                'af_advancedgallery_group_desc'              => 'Настройки галереи изображений.',
                'af_advancedgallery_enabled'                 => 'Включить галерею',
                'af_advancedgallery_items_per_page'          => 'Элементов на страницу',
                'af_advancedgallery_upload_max_mb'           => 'Макс. размер файла (МБ)',
                'af_advancedgallery_allowed_ext'             => 'Разрешённые расширения',
                'af_advancedgallery_thumb_w'                 => 'Ширина превью',
                'af_advancedgallery_thumb_h'                 => 'Высота превью',
                'af_advancedgallery_can_upload_groups'       => 'Группы с правом загрузки',
                'af_advancedgallery_can_moderate_groups'     => 'Группы модерации',
                'af_advancedgallery_autoapprove_groups'      => 'Группы автопринятия',
                'af_advancedgallery_max_albums' => 'Макс. альбомов на пользователя',
                'af_advancedgallery_max_albums_desc' => 'Макс. альбомов на пользователя (0 = без лимита).',
                'af_advancedgallery_max_media_per_album' => 'Макс. медиа в одном альбоме',
                'af_advancedgallery_max_media_per_album_desc' => 'Макс. медиа в одном альбоме (0 = без лимита).',
                'af_advancedgallery_album_visibility_default' => 'Видимость альбома по умолчанию',
                'af_advancedgallery_album_visibility_default_desc' => 'Видимость альбома по умолчанию.',
                'af_advancedgallery_remote_enabled' => 'Разрешить remote media (вставку по URL)',
                'af_advancedgallery_remote_enabled_desc' => 'Разрешить вставку медиа по URL.',
                'af_advancedgallery_remote_whitelist_domains' => 'Разрешённые домены',
                'af_advancedgallery_remote_whitelist_domains_desc' => 'Разрешённые домены (по одному в строке). Пусто = встроенный whitelist.',
                'af_advancedgallery_remote_allow_oembed' => 'Разрешить oEmbed (карточки предпросмотра)',
                'af_advancedgallery_remote_allow_oembed_desc' => 'По умолчанию выключено.',
                'af_advancedgallery_remote_cache_preview' => 'Кешировать preview/thumbnail для remote',
                'af_advancedgallery_remote_cache_preview_desc' => 'Кешировать preview/thumbnail для remote (если возможно безопасно).',
                'af_advancedgallery_remote_max_url_len' => 'Макс. длина URL',
                'af_advancedgallery_remote_max_url_len_desc' => 'Максимальная длина URL.',
            ],
        ],
        'english' => [
            'front' => [
                'af_advancedgallery_name'        => 'Gallery',
                'af_advancedgallery_description' => 'Image gallery.',
                'af_advancedgallery_albums' => 'Albums',
                'af_advancedgallery_my_albums' => 'My albums',
                'af_advancedgallery_create_album' => 'Create album',
                'af_advancedgallery_edit_album' => 'Edit album',
                'af_advancedgallery_delete_album' => 'Delete album',
                'af_advancedgallery_album_title' => 'Album title',
                'af_advancedgallery_album_desc' => 'Description',
                'af_advancedgallery_album_visibility' => 'Visibility',
                'af_advancedgallery_album_visibility_public' => 'Public',
                'af_advancedgallery_album_visibility_registered' => 'Registered only',
                'af_advancedgallery_album_visibility_private' => 'Private',
                'af_advancedgallery_album_visibility_groups' => 'Groups',
                'af_advancedgallery_album_allowed_groups' => 'Allowed groups (CSV)',
                'af_advancedgallery_album_sort_mode' => 'Sort mode',
                'af_advancedgallery_album_sort_manual' => 'Manual',
                'af_advancedgallery_album_sort_date_desc' => 'Newest first',
                'af_advancedgallery_album_sort_date_asc' => 'Oldest first',
                'af_advancedgallery_album_cover' => 'Cover (media ID)',
                'af_advancedgallery_album_empty' => 'No content yet.',
                'af_advancedgallery_album_saved' => 'Album saved.',
                'af_advancedgallery_album_deleted' => 'Album deleted.',
                'af_advancedgallery_added_to_album' => 'Add to album',
                'af_advancedgallery_removed_from_album' => 'Removed from album.',
                'af_advancedgallery_limit_albums_reached' => 'Album limit reached.',
                'af_advancedgallery_limit_media_reached' => 'Album media limit reached.',
                'af_advancedgallery_remote_add' => 'Add remote media',
                'af_advancedgallery_remote_url' => 'Media URL',
                'af_advancedgallery_remote_invalid_url' => 'Invalid URL.',
                'af_advancedgallery_remote_domain_denied' => 'Domain is not allowed.',
                'af_advancedgallery_remote_added' => 'Remote media added.',
                'af_advancedgallery_remote_album_none' => 'No album',
                'af_advancedgallery_picker_title' => 'Gallery picker',
                'af_advancedgallery_picker_insert_img' => 'Insert IMG',
                'af_advancedgallery_picker_insert_link' => 'Insert link',
                'af_advancedgallery_picker_upload_local' => 'Upload',
                'af_advancedgallery_picker_add_remote' => 'Add remote',
                'af_advancedgallery_picker_media_tab' => 'My media',
                'af_advancedgallery_picker_albums_tab' => 'My albums',
                'af_advancedgallery_picker_search' => 'Search',
                'af_advancedgallery_picker_empty' => 'No media.',
            ],
            'admin' => [
                'af_advancedgallery_group'                   => 'Gallery',
                'af_advancedgallery_group_desc'              => 'Gallery addon settings.',
                'af_advancedgallery_enabled'                 => 'Enable gallery',
                'af_advancedgallery_items_per_page'          => 'Items per page',
                'af_advancedgallery_upload_max_mb'           => 'Max upload size (MB)',
                'af_advancedgallery_allowed_ext'             => 'Allowed extensions',
                'af_advancedgallery_thumb_w'                 => 'Thumbnail width',
                'af_advancedgallery_thumb_h'                 => 'Thumbnail height',
                'af_advancedgallery_can_upload_groups'       => 'Groups allowed to upload',
                'af_advancedgallery_can_moderate_groups'     => 'Moderation groups',
                'af_advancedgallery_autoapprove_groups'      => 'Auto-approve groups',
                'af_advancedgallery_max_albums' => 'Max albums per user',
                'af_advancedgallery_max_albums_desc' => 'Max albums per user (0 = no limit).',
                'af_advancedgallery_max_media_per_album' => 'Max media per album',
                'af_advancedgallery_max_media_per_album_desc' => 'Max media per album (0 = no limit).',
                'af_advancedgallery_album_visibility_default' => 'Default album visibility',
                'af_advancedgallery_album_visibility_default_desc' => 'Default album visibility.',
                'af_advancedgallery_remote_enabled' => 'Enable remote media (URL embed)',
                'af_advancedgallery_remote_enabled_desc' => 'Allow remote media by URL.',
                'af_advancedgallery_remote_whitelist_domains' => 'Allowed domains',
                'af_advancedgallery_remote_whitelist_domains_desc' => 'Allowed domains (one per line). Empty = built-in whitelist.',
                'af_advancedgallery_remote_allow_oembed' => 'Allow oEmbed previews',
                'af_advancedgallery_remote_allow_oembed_desc' => 'Disabled by default.',
                'af_advancedgallery_remote_cache_preview' => 'Cache remote previews/thumbnails',
                'af_advancedgallery_remote_cache_preview_desc' => 'Cache remote previews/thumbnails when possible.',
                'af_advancedgallery_remote_max_url_len' => 'Max URL length',
                'af_advancedgallery_remote_max_url_len_desc' => 'Maximum allowed URL length.',
            ],
        ],
    ],
];
