<?php
/**
 * AF Addon Manifest: AdvancedThreadFields
 * MyBB 1.8.x, PHP 8.0–8.4
 */

return [
    'id'          => 'advancedthreadfields',
    'name'        => 'AdvancedThreadFields',
    'description' => 'Дополнительные поля для тем (как XThreads): ввод в newthread/editpost, хранение значений, вывод в showthread/forumdisplay, фильтры.',
    'version'     => '1.0.0',
    'author'   => 'CaptainPaws',
    'website'     => 'https://github.com/CaptainPaws',
    'bootstrap'   => 'advancedthreadfields.php',

    'admin' => [
        'slug'       => 'advancedthreadfields',
        'controller' => 'admin.php',
        'name'       => 'Поля тем',
        'icon'       => 'fas fa-list-alt',
        'order'      => 30,
    ],

    /**
     * Языковые пакеты генерируются ядром AF по этим ключам.
     * Здесь важно иметь и RU и EN тексты (front/admin).
     */
    'lang' => [
        'front' => [
            // RU
            'af_atf_name_ru'        => 'AdvancedThreadFields',
            'af_atf_description_ru' => 'Дополнительные поля для тем.',
            'af_atf_type_kb_race_ru'  => 'KB выбор: раса',
            'af_atf_type_kb_class_ru' => 'KB выбор: класс',
            'af_atf_type_kb_theme_ru' => 'KB выбор: тема',
            'af_atf_type_sf_attributes_pointbuy_ru' => 'SF атрибуты (point-buy)',
            'af_atf_sf_total_points_ru' => 'Всего поинтов',
            'af_atf_sf_spent_ru' => 'Потрачено',
            'af_atf_sf_remaining_ru' => 'Осталось',
            'af_atf_sf_group_mental_ru' => 'Ментальная группа',
            'af_atf_sf_group_combat_ru' => 'Боевая группа',
            'af_atf_sf_group_physical_ru' => 'Физическая группа',
            'af_atf_sf_err_overbudget_ru' => 'Превышен лимит поинтов',
            'af_atf_sf_err_out_of_range_ru' => 'Значение выходит за пределы',
            'af_atf_sf_err_not_exact_ru' => 'Нужно потратить ровно все поинты',
            'af_atf_attr_int_ru' => 'Интеллект',
            'af_atf_attr_will_ru' => 'Сила воли',
            'af_atf_attr_pre_ru' => 'Присутствие',
            'af_atf_attr_tech_ru' => 'Техника',
            'af_atf_attr_ref_ru' => 'Рефлексы',
            'af_atf_attr_dex_ru' => 'Ловкость',
            'af_atf_attr_con_ru' => 'Телосложение',
            'af_atf_attr_str_ru' => 'Сила',
            'af_atf_attr_body_ru' => 'Тело',
            'af_atf_group_mental_ru' => 'Ментальная группа',
            'af_atf_group_combat_ru' => 'Боевая группа',
            'af_atf_group_physical_ru' => 'Физическая группа',

            // EN
            'af_atf_name_en'        => 'AdvancedThreadFields',
            'af_atf_description_en' => 'Additional thread fields.',
            'af_atf_type_kb_race_en'  => 'KB select: Race',
            'af_atf_type_kb_class_en' => 'KB select: Class',
            'af_atf_type_kb_theme_en' => 'KB select: Theme',
            'af_atf_type_sf_attributes_pointbuy_en' => 'SF attributes (point-buy)',
            'af_atf_sf_total_points_en' => 'Total points',
            'af_atf_sf_spent_en' => 'Spent',
            'af_atf_sf_remaining_en' => 'Remaining',
            'af_atf_sf_group_mental_en' => 'Mental Group',
            'af_atf_sf_group_combat_en' => 'Combat Group',
            'af_atf_sf_group_physical_en' => 'Physical Group',
            'af_atf_sf_err_overbudget_en' => 'Point budget exceeded',
            'af_atf_sf_err_out_of_range_en' => 'Value out of range',
            'af_atf_sf_err_not_exact_en' => 'You must spend exactly all points',
            'af_atf_attr_int_en' => 'Intelligence',
            'af_atf_attr_will_en' => 'Willpower',
            'af_atf_attr_pre_en' => 'Presence',
            'af_atf_attr_tech_en' => 'Technique',
            'af_atf_attr_ref_en' => 'Reflexes',
            'af_atf_attr_dex_en' => 'Dexterity',
            'af_atf_attr_con_en' => 'Constitution',
            'af_atf_attr_str_en' => 'Strength',
            'af_atf_attr_body_en' => 'Body',
            'af_atf_group_mental_en' => 'Mental Group',
            'af_atf_group_combat_en' => 'Combat Group',
            'af_atf_group_physical_en' => 'Physical Group',
        ],

        'admin' => [
            // RU
            'af_atf_group_ru'        => 'AdvancedThreadFields',
            'af_atf_group_desc_ru'   => 'Настройки и управление полями для тем.',
            'af_atf_enabled_ru'      => 'Включить AdvancedThreadFields',
            'af_atf_enabled_desc_ru' => 'Включает обработку полей тем на форуме.',

            'af_atf_nav_fields_ru'   => 'Поля тем',
            'af_atf_nav_add_ru'      => 'Добавить поле',
            'af_atf_nav_edit_ru'     => 'Редактировать поле',
            'af_atf_nav_delete_ru'   => 'Удалить поле',

            'af_atf_field_title_ru'     => 'Название (title)',
            'af_atf_field_name_ru'      => 'Ключ (name)',
            'af_atf_field_desc_ru'      => 'Описание',
            'af_atf_field_type_ru'      => 'Тип',
            'af_atf_field_options_ru'   => 'Опции (для select/radio/checkboxgroup)',
            'af_atf_field_required_ru'  => 'Обязательное',
            'af_atf_field_active_ru'    => 'Активное',
            'af_atf_field_forums_ru'    => 'Форумы (ID через запятую; пусто = везде)',
            'af_atf_field_show_thread_ru' => 'Показывать в теме',
            'af_atf_field_show_forum_ru'  => 'Показывать в списке тем',
            'af_atf_field_sort_ru'        => 'Порядок',
            'af_atf_field_maxlen_ru'      => 'Макс. длина',
            'af_atf_field_regex_ru'       => 'Regex валидации',
            'af_atf_field_format_ru'      => 'Формат вывода (используй {LABEL} и {VALUE})',

            'af_atf_btn_save_ru'     => 'Сохранить',
            'af_atf_btn_delete_ru'   => 'Удалить',
            'af_atf_confirm_delete_ru' => 'Удалить поле и все его значения?',
            'af_atf_type_kb_race_ru'  => 'KB выбор: раса',
            'af_atf_type_kb_class_ru' => 'KB выбор: класс',
            'af_atf_type_kb_theme_ru' => 'KB выбор: тема',
            'af_atf_type_sf_attributes_pointbuy_ru' => 'SF атрибуты (point-buy)',
            'af_atf_sf_total_points_ru' => 'Всего поинтов',
            'af_atf_sf_spent_ru' => 'Потрачено',
            'af_atf_sf_remaining_ru' => 'Осталось',
            'af_atf_sf_group_mental_ru' => 'Ментальная группа',
            'af_atf_sf_group_combat_ru' => 'Боевая группа',
            'af_atf_sf_group_physical_ru' => 'Физическая группа',
            'af_atf_sf_err_overbudget_ru' => 'Превышен лимит поинтов',
            'af_atf_sf_err_out_of_range_ru' => 'Значение выходит за пределы',
            'af_atf_sf_err_not_exact_ru' => 'Нужно потратить ровно все поинты',
            'af_atf_attr_int_ru' => 'Интеллект',
            'af_atf_attr_will_ru' => 'Сила воли',
            'af_atf_attr_pre_ru' => 'Присутствие',
            'af_atf_attr_tech_ru' => 'Техника',
            'af_atf_attr_ref_ru' => 'Рефлексы',
            'af_atf_attr_dex_ru' => 'Ловкость',
            'af_atf_attr_con_ru' => 'Телосложение',
            'af_atf_attr_str_ru' => 'Сила',
            'af_atf_attr_body_ru' => 'Тело',
            'af_atf_group_mental_ru' => 'Ментальная группа',
            'af_atf_group_combat_ru' => 'Боевая группа',
            'af_atf_group_physical_ru' => 'Физическая группа',

            // EN
            'af_atf_group_en'        => 'AdvancedThreadFields',
            'af_atf_group_desc_en'   => 'Settings and management for thread fields.',
            'af_atf_enabled_en'      => 'Enable AdvancedThreadFields',
            'af_atf_enabled_desc_en' => 'Enables thread fields processing on the board.',

            'af_atf_nav_fields_en'   => 'Thread fields',
            'af_atf_nav_add_en'      => 'Add field',
            'af_atf_nav_edit_en'     => 'Edit field',
            'af_atf_nav_delete_en'   => 'Delete field',

            'af_atf_field_title_en'     => 'Title',
            'af_atf_field_name_en'      => 'Key (name)',
            'af_atf_field_desc_en'      => 'Description',
            'af_atf_field_type_en'      => 'Type',
            'af_atf_field_options_en'   => 'Options (for select/radio/checkboxgroup)',
            'af_atf_field_required_en'  => 'Required',
            'af_atf_field_active_en'    => 'Active',
            'af_atf_field_forums_en'    => 'Forums (IDs comma-separated; empty = all)',
            'af_atf_field_show_thread_en' => 'Show in thread',
            'af_atf_field_show_forum_en'  => 'Show in thread list',
            'af_atf_field_sort_en'        => 'Sort order',
            'af_atf_field_maxlen_en'      => 'Max length',
            'af_atf_field_regex_en'       => 'Validation regex',
            'af_atf_field_format_en'      => 'Display format (use {LABEL} and {VALUE})',

            'af_atf_btn_save_en'     => 'Save',
            'af_atf_btn_delete_en'   => 'Delete',
            'af_atf_confirm_delete_en' => 'Delete this field and all its values?',
            'af_atf_type_kb_race_en'  => 'KB select: Race',
            'af_atf_type_kb_class_en' => 'KB select: Class',
            'af_atf_type_kb_theme_en' => 'KB select: Theme',
            'af_atf_type_sf_attributes_pointbuy_en' => 'SF attributes (point-buy)',
            'af_atf_sf_total_points_en' => 'Total points',
            'af_atf_sf_spent_en' => 'Spent',
            'af_atf_sf_remaining_en' => 'Remaining',
            'af_atf_sf_group_mental_en' => 'Mental Group',
            'af_atf_sf_group_combat_en' => 'Combat Group',
            'af_atf_sf_group_physical_en' => 'Physical Group',
            'af_atf_sf_err_overbudget_en' => 'Point budget exceeded',
            'af_atf_sf_err_out_of_range_en' => 'Value out of range',
            'af_atf_sf_err_not_exact_en' => 'You must spend exactly all points',
            'af_atf_attr_int_en' => 'Intelligence',
            'af_atf_attr_will_en' => 'Willpower',
            'af_atf_attr_pre_en' => 'Presence',
            'af_atf_attr_tech_en' => 'Technique',
            'af_atf_attr_ref_en' => 'Reflexes',
            'af_atf_attr_dex_en' => 'Dexterity',
            'af_atf_attr_con_en' => 'Constitution',
            'af_atf_attr_str_en' => 'Strength',
            'af_atf_attr_body_en' => 'Body',
            'af_atf_group_mental_en' => 'Mental Group',
            'af_atf_group_combat_en' => 'Combat Group',
            'af_atf_group_physical_en' => 'Physical Group',
        ],
    ],
];
