<?php
if (!defined('IN_MYBB') || !defined('IN_ADMINCP')) die('No direct access');
class AF_Admin_Advancedwanted {
 public static function dispatch(string $action=''): string { $html=self::render();echo $html;return $html; }
 public static function render(): string { global $db,$mybb;
  $tab=in_array($mybb->get_input('tab'),['entries','fields','settings'],true)?$mybb->get_input('tab'):'entries';
  if($mybb->request_method==='post'){verify_post_check($mybb->get_input('my_post_key'));$do=$mybb->get_input('do');
   if($do==='save_field'){ $id=(int)$mybb->get_input('id');$key=preg_replace('~[^a-z0-9_]+~','',strtolower($mybb->get_input('field_key')));$type=$mybb->get_input('type');if(!in_array($type,['text','textarea','url','image','number','select','multi','checkbox','radio','kb_dynamic'],true))$type='text';$settings=['source'=>trim($mybb->get_input('source')),'depends_on'=>trim($mybb->get_input('depends_on')),'filterable'=>(bool)$mybb->get_input('filterable'),'show_card'=>(bool)$mybb->get_input('show_card'),'show_detail'=>(bool)$mybb->get_input('show_detail'),'options'=>[]];foreach(preg_split('~\R~',trim($mybb->get_input('options'))) as $line){if(strpos($line,'=')!==false){[$k,$v]=array_map('trim',explode('=',$line,2));if($k!=='')$settings['options'][$k]=$v;}}$data=['field_key'=>$db->escape_string($key),'title'=>$db->escape_string(trim($mybb->get_input('title'))),'type'=>$type,'required'=>(int)(bool)$mybb->get_input('required'),'active'=>(int)(bool)$mybb->get_input('active'),'sortorder'=>(int)$mybb->get_input('sortorder'),'settings_json'=>$db->escape_string(json_encode($settings,JSON_UNESCAPED_UNICODE))];if($id)$db->update_query(AF_WANTED_FIELDS,$data,'id='.$id);else$db->insert_query(AF_WANTED_FIELDS,$data);admin_redirect('index.php?module=advancedfunctionality&af_view=advancedwanted&tab=fields');}
   if($do==='delete_field'){ $id=(int)$mybb->get_input('id');$used=(int)$db->fetch_field($db->simple_select(AF_WANTED_VALUES,'COUNT(*) c','field_id='.$id),'c');if(!$used)$db->delete_query(AF_WANTED_FIELDS,'id='.$id);else flash_message('Поле используется и не может быть удалено.','error');admin_redirect('index.php?module=advancedfunctionality&af_view=advancedwanted&tab=fields');}
   if($do==='delete_entry'){ $id=(int)$mybb->get_input('id');$db->delete_query(AF_WANTED_VALUES,'wanted_id='.$id);$db->delete_query(AF_WANTED_ENTRIES,'id='.$id);admin_redirect('index.php?module=advancedfunctionality&af_view=advancedwanted');}
   if($do==='entry_status'){ $id=(int)$mybb->get_input('id');$status=$mybb->get_input('status');if(in_array($status,['open','reserved','application','archived'],true)){$data=['status'=>$status,'updated_at'=>TIME_NOW];if($status==='open')$data+=['reserved_by_uid'=>null,'reserved_at'=>0,'application_tid'=>null,'accepted_uid'=>null,'archived_at'=>0];if($status==='archived')$data['archived_at']=TIME_NOW;$db->update_query(AF_WANTED_ENTRIES,$data,'id='.$id);}admin_redirect('index.php?module=advancedfunctionality&af_view=advancedwanted');}
  }
  $base='index.php?module=advancedfunctionality&af_view=advancedwanted';$h='<h1>AdvancedWanted</h1><p><a href="'.$base.'&tab=entries">Записи</a> | <a href="'.$base.'&tab=fields">Поля формы</a> | <a href="'.$base.'&tab=settings">Настройки</a></p>';
  if($tab==='settings')return $h.'<p>Права групп, forum ID и pagination настраиваются в Configuration → Settings → AdvancedWanted.</p>';
  if($tab==='fields'){ $h.='<table class="general"><tr><th>Название</th><th>Ключ</th><th>Тип</th><th>Обязательно</th><th>Активно</th><th>Порядок</th><th>Действия</th></tr>';foreach(af_wanted_fields(false) as $f)$h.='<tr><td>'.htmlspecialchars_uni($f['title']).'</td><td>'.$f['field_key'].'</td><td>'.$f['type'].'</td><td>'.($f['required']?'Да':'Нет').'</td><td>'.($f['active']?'Да':'Нет').'</td><td>'.$f['sortorder'].'</td><td><a href="'.$base.'&tab=fields&edit='.(int)$f['id'].'">Изменить</a> <form method="post" style="display:inline"><input type="hidden" name="my_post_key" value="'.$mybb->post_code.'"><input type="hidden" name="do" value="delete_field"><input type="hidden" name="id" value="'.(int)$f['id'].'"><button>Удалить</button></form></td></tr>';$h.='</table>';$edit=(int)$mybb->get_input('edit');$f=$edit?(array)$db->fetch_array($db->simple_select(AF_WANTED_FIELDS,'*','id='.$edit)):[];$s=json_decode((string)($f['settings_json']??''),true)?:[];$opts='';foreach((array)($s['options']??[]) as $k=>$v)$opts.="$k=$v\n";$h.='<h2>'.($edit?'Изменить':'Создать').' поле</h2><form method="post"><input type="hidden" name="my_post_key" value="'.$mybb->post_code.'"><input type="hidden" name="do" value="save_field"><input type="hidden" name="id" value="'.$edit.'">'.self::input('title','Название',$f['title']??'').self::input('field_key','Ключ',$f['field_key']??'').'<label>Тип <select name="type">';foreach(['text','textarea','url','image','number','select','multi','checkbox','radio','kb_dynamic'] as $t)$h.='<option'.(($f['type']??'')===$t?' selected':'').'>'.$t.'</option>';$h.='</select></label>'.self::input('source','Option source',$s['source']??'').self::input('depends_on','Depends on',$s['depends_on']??'').'<label>Options key=label<textarea name="options">'.htmlspecialchars_uni($opts).'</textarea></label>';foreach(['required'=>'Обязательно','active'=>'Активно','filterable'=>'Filterable','show_card'=>'Show in card','show_detail'=>'Show in detail'] as $k=>$l){$val=array_key_exists($k,$f)?$f[$k]:($s[$k]??($k==='active'));$h.='<label><input type="checkbox" name="'.$k.'" value="1"'.($val?' checked':'').'> '.$l.'</label>';}$h.=self::input('sortorder','Порядок',$f['sortorder']??0).'<button type="submit">Сохранить</button></form>';return $h; }
  $h.='<table class="general"><tr><th>ID</th><th>Автор</th><th>Статус</th><th>Reserved UID</th><th>TID</th><th>Accepted UID</th><th>Создано</th><th>Действия</th></tr>';$q=$db->write_query('SELECT e.*,u.username FROM '.TABLE_PREFIX.AF_WANTED_ENTRIES.' e LEFT JOIN '.TABLE_PREFIX.'users u ON u.uid=e.author_uid ORDER BY e.id DESC LIMIT 100');while($e=$db->fetch_array($q)){$h.='<tr><td>'.$e['id'].'</td><td>'.htmlspecialchars_uni($e['username']).'</td><td>'.$e['status'].'</td><td>'.(int)$e['reserved_by_uid'].'</td><td>'.(int)$e['application_tid'].'</td><td>'.(int)$e['accepted_uid'].'</td><td>'.my_date('relative',$e['created_at']).'</td><td><form method="post"><input type="hidden" name="my_post_key" value="'.$mybb->post_code.'"><input type="hidden" name="do" value="entry_status"><input type="hidden" name="id" value="'.$e['id'].'"><select name="status">';foreach(['open','reserved','application','archived'] as $st)$h.='<option'.($e['status']===$st?' selected':'').'>'.$st.'</option>';$h.='</select><button>Сохранить</button></form><form method="post"><input type="hidden" name="my_post_key" value="'.$mybb->post_code.'"><input type="hidden" name="do" value="delete_entry"><input type="hidden" name="id" value="'.$e['id'].'"><button>Удалить</button></form></td></tr>';}$h.='</table>';return $h;
 }
 private static function input(string $n,string $l,$v): string{return '<label>'.$l.' <input name="'.$n.'" value="'.htmlspecialchars_uni((string)$v).'"></label>';}
}
