<?php
return [
    'id'          => 'knowledgebase',
    'name'        => 'База знаний',
    'version'     => '1.0.0',
    'author'      => 'AdvancedFunctionality',
    'authorsite'  => '',
    'description' => 'Единая база знаний для сущностей (type/key).',
    'bootstrap'   => 'knowledgebase.php',
    'admin' => [
        'slug'       => 'knowledgebase',
        'title'      => 'Knowledge Base',
        'controller' => 'admin.php',
    ],
    'lang' => [
        'russian' => [
            'front' => [
                'af_knowledgebase_name'        => 'База знаний',
                'af_knowledgebase_description' => 'Единое хранилище сущностей (type/key).',
                'af_kb_catalog_title'          => 'Каталог базы знаний',
                'af_kb_search_placeholder'     => 'Поиск по базе знаний...',
                'af_kb_edit'                   => 'Редактировать',
                'af_kb_create'                 => 'Создать запись',
                'af_kb_save'                   => 'Сохранить',
                'af_kb_cancel'                 => 'Отмена',
                'af_kb_delete'                 => 'Удалить',
                'af_kb_no_access'              => 'Нет доступа к базе знаний.',
                'af_kb_not_found'              => 'Запись не найдена.',
                'af_kb_invalid_key'            => 'Некорректный ключ записи.',
                'af_kb_invalid_json'           => 'Ошибка в JSON-полях.',
            ],
            'admin' => [
                'af_knowledgebase_group'             => 'AF: База знаний',
                'af_knowledgebase_group_desc'        => 'Настройки аддона «База знаний».',
                'af_knowledgebase_enabled'           => 'Включить базу знаний',
                'af_knowledgebase_enabled_desc'      => 'Да/Нет',
                'af_kb_public_catalog'               => 'Публичный каталог',
                'af_kb_public_catalog_desc'          => 'Показывать каталог всем пользователям.',
                'af_kb_editor_groups'                => 'Группы редакторов',
                'af_kb_editor_groups_desc'           => 'CSV ID групп, которым разрешено редактирование.',
                'af_kb_types_manage_groups'          => 'Группы управления типами',
                'af_kb_types_manage_groups_desc'     => 'CSV ID групп, которым разрешено управлять типами.',
                'af_kb_atf_map'                       => 'ATF → KB маппинг',
                'af_kb_atf_map_desc'                  => 'JSON соответствий поля ATF → тип KB.',
            ],
        ],
        'english' => [
            'front' => [
                'af_knowledgebase_name'        => 'Knowledge Base',
                'af_knowledgebase_description' => 'Single source of truth for entities (type/key).',
                'af_kb_catalog_title'          => 'Knowledge Base Catalog',
                'af_kb_search_placeholder'     => 'Search knowledge base...',
                'af_kb_edit'                   => 'Edit',
                'af_kb_create'                 => 'Create entry',
                'af_kb_save'                   => 'Save',
                'af_kb_cancel'                 => 'Cancel',
                'af_kb_delete'                 => 'Delete',
                'af_kb_no_access'              => 'No access to knowledge base.',
                'af_kb_not_found'              => 'Entry not found.',
                'af_kb_invalid_key'            => 'Invalid entry key.',
                'af_kb_invalid_json'           => 'JSON validation error.',
            ],
            'admin' => [
                'af_knowledgebase_group'             => 'AF: Knowledge Base',
                'af_knowledgebase_group_desc'        => 'Settings for Knowledge Base addon.',
                'af_knowledgebase_enabled'           => 'Enable Knowledge Base',
                'af_knowledgebase_enabled_desc'      => 'Yes/No',
                'af_kb_public_catalog'               => 'Public catalog',
                'af_kb_public_catalog_desc'          => 'Show catalog for everyone.',
                'af_kb_editor_groups'                => 'Editor groups',
                'af_kb_editor_groups_desc'           => 'CSV of group IDs that can edit.',
                'af_kb_types_manage_groups'          => 'Type management groups',
                'af_kb_types_manage_groups_desc'     => 'CSV of group IDs that can manage types.',
                'af_kb_atf_map'                       => 'ATF → KB mapping',
                'af_kb_atf_map_desc'                  => 'JSON mapping of ATF field → KB type.',
            ],
        ],
    ],
];
