<?php

return [
    'id'          => 'characterworkflow',
    'name'        => 'CharacterWorkflow',
    'description' => 'Оркестратор модерационного workflow анкеты персонажа.',
    'version'     => '0.1.0',
    'author'      => 'CaptainPaws',
    'website'     => 'https://github.com/CaptainPaws',
    'bootstrap'   => 'characterworkflow.php',
    'lang' => [
        'russian' => [
            'front' => [
                'af_characterworkflow_name' => 'CharacterWorkflow',
                'af_characterworkflow_description' => 'Оркестрация workflow модерации анкеты персонажа.',
            ],
            'admin' => [
                'af_characterworkflow_group' => 'AF: CharacterWorkflow',
                'af_characterworkflow_group_desc' => 'Настройки оркестратора workflow анкеты.',
                'af_characterworkflow_enabled' => 'Включить CharacterWorkflow',
                'af_characterworkflow_enabled_desc' => 'Включает таблицу состояний и API оркестрации модерации анкеты.',
                'af_characterworkflow_pending_forums' => 'Форумы ожидания анкет',
                'af_characterworkflow_pending_forums_desc' => 'CSV id форумов, где темы считаются анкетами в ожидании модерации.',
                'af_characterworkflow_target_forums' => 'Форумы назначения (accepted)',
                'af_characterworkflow_target_forums_desc' => 'CSV id форумов, куда переводится анкета после принятия.',
                'af_characterworkflow_transfer_group_ids' => 'Дополнительные группы при переводе',
                'af_characterworkflow_transfer_group_ids_desc' => 'CSV gid для добавления в additional groups автору анкеты после перевода (без смены основной группы).',
                'af_characterworkflow_greeting_mode' => 'Поведение приветственного поста',
                'af_characterworkflow_greeting_mode_desc' => 'inherit = логика CharacterSheets, always = всегда пытаться постить, never = не постить.',
                'af_characterworkflow_canon_source_policy' => 'Policy источника истины для канонов',
                'af_characterworkflow_canon_source_policy_desc' => 'Для канонов источник истины — KB.',
                'af_characterworkflow_original_source_policy' => 'Policy источника истины для авторских',
                'af_characterworkflow_original_source_policy_desc' => 'Для авторских до KB источник — тема/ATF, после создания — KB.',
            ],
        ],
        'english' => [
            'front' => [
                'af_characterworkflow_name' => 'CharacterWorkflow',
                'af_characterworkflow_description' => 'Orchestrates character application moderation workflow.',
            ],
            'admin' => [
                'af_characterworkflow_group' => 'AF: CharacterWorkflow',
                'af_characterworkflow_group_desc' => 'Character application workflow orchestrator settings.',
                'af_characterworkflow_enabled' => 'Enable CharacterWorkflow',
                'af_characterworkflow_enabled_desc' => 'Enables workflow state table and moderation orchestration API.',
                'af_characterworkflow_pending_forums' => 'Pending application forums',
                'af_characterworkflow_pending_forums_desc' => 'CSV forum IDs where threads are treated as pending character applications.',
                'af_characterworkflow_target_forums' => 'Target accepted forum ids',
                'af_characterworkflow_target_forums_desc' => 'CSV forum IDs used as transfer target(s).',
                'af_characterworkflow_transfer_group_ids' => 'Additional groups on transfer',
                'af_characterworkflow_transfer_group_ids_desc' => 'CSV group IDs added to the thread author additional groups after transfer (without changing primary group).',
                'af_characterworkflow_greeting_mode' => 'Greeting behavior',
                'af_characterworkflow_greeting_mode_desc' => 'inherit = CharacterSheets logic, always = always attempt greeting post, never = do not post greeting.',
                'af_characterworkflow_canon_source_policy' => 'Canon source-of-truth policy',
                'af_characterworkflow_canon_source_policy_desc' => 'For canon characters KB stays source-of-truth.',
                'af_characterworkflow_original_source_policy' => 'Original source-of-truth policy',
                'af_characterworkflow_original_source_policy_desc' => 'For originals source starts from thread/ATF then can sync to KB.',
            ],
        ],
    ],
];
